sex = {'man': 'Мужское',
       'woman': 'Женское',
       'child': 'Детское',
       'Мужское': 'man',
       'Женское': 'woman',
       'Детское': 'child',
    }

categories = {'Одежда': 'wear',
            'Обувь': 'shoes',
            'Аксессуары': 'accessories',
            'Косметика': 'cosmetics',
            'Игрушки': 'toys',
            'Другое': 'other',
    }

sizes = {'2XS': 'size1',
         'XS': 'size2',
         'M': 'size3',
         'L': 'size4',
         'XL': 'size5',
         '2XL': 'size6',
         '3XL': 'size7',
         '4XL': 'size8',
         '6.5US': 'size1',
         '7US': 'size2',
         '7.5US': 'size3',
         '8US': 'size4',
         '8.5US': 'size5',
         '9US': 'size6',
         '9.5US': 'size7',
         '10US': 'size8',
         '10.5US': 'size9',
         '11US': 'size10',
         '11.5US': 'size11',
         '10см': 'size11',
         '11см': 'size11',
         '12см': 'size12',
         '13см': 'size13',
         '14см': 'size14',
         '15см': 'size15',
         '16см': 'size16',
         '17см': 'size17',
         '18см': 'size18',
         '19см': 'size19',
         '20см': 'size20',
         '21см': 'size21',
         '22см': 'size22',
         '23см': 'size23',
         '24см': 'size24',
         '25см': 'size25',
         '26см': 'size26',
         '27см': 'size27',
         '28см': 'size28',
         '29см': 'size29',
         '30см': 'size30',
    }
